import React, { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, CheckCircle2, Clock, Code2, Database, GitBranch, HardDrive, RefreshCw, Server, ShieldAlert, Users, WifiOff } from "lucide-react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type ApiEnvelope = { heartbeat?: any; control_center?: any; uptime?: any[]; incidents?: any[]; deploy?: any; server?: any; api_traffic?: any; backup?: any; request_summary?: any; request_events?: any[] };
type HistoryEnvelope = { server?: any[]; traffic?: any[]; uptime?: any[]; requests?: any[] };
type ChartDatum = { label: string; value: number; tone?: string };
const API_BASE = import.meta.env.VITE_OPS_API_BASE || "/api";

const asArray = <T,>(value: unknown): T[] => Array.isArray(value) ? value as T[] : [];
const parseJson = (value: unknown): any => { if (typeof value !== "string") return value || {}; try { return JSON.parse(value); } catch { return {}; } };
const parseArray = (value: unknown): any[] => asArray(parseJson(value));
const parseObject = (value: unknown): Record<string, any> => { const p = parseJson(value); return p && typeof p === "object" && !Array.isArray(p) ? p : {}; };
const n = (value: any, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
function statusClass(status?: string | null): string { const value = String(status || "unknown").toLowerCase(); if (["healthy", "ok", "active", "running", "online", "live", "enabled"].includes(value)) return "good"; if (["degraded", "warning", "pending", "stale", "partial"].includes(value)) return "warn"; if (["critical", "failed", "down", "inactive", "error", "missing", "disabled"].includes(value)) return "bad"; return "unknown"; }
function formatAgo(iso?: string): string { if (!iso) return "never"; const diff = Date.now() - new Date(iso).getTime(); if (!Number.isFinite(diff)) return "unknown"; const s = Math.max(0, Math.round(diff / 1000)); if (s < 60) return `${s}s ago`; const m = Math.round(s / 60); if (m < 60) return `${m}m ago`; const h = Math.round(m / 60); if (h < 48) return `${h}h ago`; return `${Math.round(h / 24)}d ago`; }
function fmtUptime(seconds?: number | null): string { if (!seconds && seconds !== 0) return "—"; const d = Math.floor(seconds / 86400), h = Math.floor((seconds % 86400) / 3600), m = Math.floor((seconds % 3600) / 60); return d ? `${d}d ${h}h` : h ? `${h}h ${m}m` : `${m}m`; }
function fmtBytes(bytes?: number | null): string { const b = n(bytes, -1); if (b < 0) return "—"; if (b < 1024 * 1024) return `${Math.round(b / 1024)} KB`; if (b < 1024 ** 3) return `${(b / 1024 ** 2).toFixed(1)} MB`; return `${(b / 1024 ** 3).toFixed(2)} GB`; }
async function fetchJson<T>(path: string): Promise<T> { const res = await fetch(`${API_BASE}${path}`, { cache: "no-store" }); if (!res.ok) throw new Error(`${res.status} ${res.statusText}`); return await res.json() as T; }

function MetricCard({ title, value, detail, icon, tone }: { title: string; value: React.ReactNode; detail?: React.ReactNode; icon: React.ReactNode; tone?: string }) { return <section className={`metric ${tone || ""}`}><div className="metricIcon">{icon}</div><div><p>{title}</p><strong>{value}</strong>{detail ? <span>{detail}</span> : null}</div></section>; }
function BarChart({ data }: { data: ChartDatum[] }) { const rows = asArray<ChartDatum>(data); const max = Math.max(...rows.map((d) => n(d.value)), 1); return <div className="chartBars">{rows.map((d) => <div className="barRow" key={d.label}><span className="barLabel" title={d.label}>{d.label}</span><div className="barTrack"><div className={`barFill ${d.tone || ""}`} style={{ width: `${Math.max(2, n(d.value) / max * 100)}%` }} /></div><span className="barValue">{d.value}</span></div>)}</div>; }
function Sparkline({ values, label, tone, suffix = "" }: { values: number[]; label: string; tone?: string; suffix?: string }) { const nums = asArray<number>(values).map(Number).filter(Number.isFinite); const max = Math.max(...nums, 1), min = Math.min(...nums, 0), span = Math.max(1, max - min); const points = nums.length ? nums.map((v, i) => `${(i / Math.max(1, nums.length - 1)) * 100},${42 - ((v - min) / span) * 34}`).join(" ") : "0,42 100,42"; return <div className="sparkBox"><div className="sparkHeader"><strong>{label}</strong><span>{nums.length ? `${nums[nums.length - 1]}${suffix}` : "0"}</span></div><svg className={`spark ${tone || ""}`} viewBox="0 0 100 48" preserveAspectRatio="none"><polyline points={points} /></svg></div>; }
function HeatStrip({ items }: { items: any[] }) { const rows = asArray<any>(items).slice(-60); return <div className="heatStrip">{rows.map((x, i) => { const status = n(x?.status || x?.status_code, 200); const cls = x?.ok || status < 400 ? "good" : status < 500 ? "warn" : "bad"; return <span key={`${x?.checked_at || x?.ts || i}-${i}`} className={`heatCell ${cls}`} title={`${x?.target_key || x?.endpoint || "target"} ${x?.status_code || x?.status || "—"} ${formatAgo(x?.checked_at || x?.ts)}`} />; })}</div>; }
function KV({ label, value }: { label: string; value: React.ReactNode }) { return <div className="kv"><span>{label}</span><strong>{value}</strong></div>; }
function Section({ id, eyebrow, title, subtitle, children }: { id: string; eyebrow: string; title: string; subtitle?: string; children: React.ReactNode }) { return <section className="section" id={id}><div className="sectionHead"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{subtitle ? <p>{subtitle}</p> : null}</div></div>{children}</section>; }
function StatusRow({ name, status, detail }: { name: string; status: string; detail?: React.ReactNode }) { return <article className="statusRow"><span className={`dot ${statusClass(status)}`} /><div><strong>{name}</strong><p>{status}{detail ? <> · {detail}</> : null}</p></div></article>; }
function CoverageCard({ title, detail }: { title: string; detail: string }) { return <article className="coverageCard good"><span className="pill good">live</span><strong>{title}</strong><p>{detail}</p></article>; }

function App() {
  const [latest, setLatest] = useState<ApiEnvelope | null>(null); const [services, setServices] = useState<any[]>([]); const [history, setHistory] = useState<HistoryEnvelope | null>(null); const [errors, setErrors] = useState<any[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [lastRefresh, setLastRefresh] = useState<string | null>(null);
  const load = async () => { setLoading(true); setError(null); try { const [latestPayload, servicePayload, errorPayload, historyPayload] = await Promise.all([fetchJson<ApiEnvelope>("/status/latest"), fetchJson<any>("/services"), fetchJson<any>("/errors"), fetchJson<HistoryEnvelope>("/history")]); setLatest(latestPayload); setServices(asArray(servicePayload?.services)); setErrors(asArray(errorPayload?.error_groups)); setHistory(historyPayload); setLastRefresh(new Date().toISOString()); } catch (exc) { setError(exc instanceof Error ? exc.message : "Unable to load dashboard data"); } finally { setLoading(false); } };
  useEffect(() => { void load(); const id = window.setInterval(() => void load(), 60_000); return () => window.clearInterval(id); }, []);

  const heartbeat = latest?.heartbeat || {}; const cc = latest?.control_center || {}; const production = cc.production || {}; const database = cc.database || {}; const queue = cc.queue || {}; const business = cc.business || {}; const security = cc.security || {}; const ux = cc.user_experience || {}; const deployment = cc.deployment || {}; const summary = useMemo(() => parseObject(heartbeat?.summary_json), [heartbeat]);
  const status = String(heartbeat?.status || "unknown"); const uptime = asArray<any>(latest?.uptime); const incidents = asArray<any>(latest?.incidents); const server = latest?.server || {}; const backup = latest?.backup || {}; const apiTraffic = latest?.api_traffic || {}; const requestSummary = latest?.request_summary || {}; const requestEvents = asArray<any>(latest?.request_events); const histServer = asArray<any>(history?.server); const histTraffic = asArray<any>(history?.traffic); const histUptime = asArray<any>(history?.uptime); const histRequests = asArray<any>(history?.requests);
  const statusCodes = parseObject(apiTraffic.status_codes_json); const topPaths = parseArray(apiTraffic.top_paths_json); const requestRoles = parseObject(requestSummary.roles_json); const requestEndpoints = parseArray(requestSummary.endpoints_json);
  const serviceChart = [{ label: "active", value: services.filter((s) => statusClass(s.status) === "good").length, tone: "good" }, { label: "warning", value: services.filter((s) => statusClass(s.status) === "warn").length, tone: "warn" }, { label: "bad", value: services.filter((s) => statusClass(s.status) === "bad").length, tone: "bad" }];
  const statusChart = Object.entries(statusCodes).map(([label, value]) => ({ label, value: n(value), tone: n(label) >= 500 ? "bad" : n(label) >= 400 ? "warn" : "good" }));
  const roleChart = Object.entries(requestRoles).map(([label, value]) => ({ label, value: n(value), tone: label === "anonymous" ? "warn" : "good" }));
  const endpointChart = requestEndpoints.slice(0, 8).map((x: any) => ({ label: String(x?.endpoint || x?.path || "unknown"), value: n(x?.count), tone: "good" }));
  const diskTrend = histServer.map((x) => n(x?.disk_used_pct)); const memoryTrend = histServer.map((x) => n(x?.memory_used_pct)); const loadTrend = histServer.map((x) => n(x?.load1)); const requestTrend = histTraffic.map((x) => n(x?.total_requests)); const errorTrend = histTraffic.map((x) => n(x?.total_5xx)); const latencyTrend = histUptime.map((x) => n(x?.latency_ms)); const durationTrend = (histRequests.length ? histRequests : requestEvents).map((x) => n(x?.duration_ms));
  const queues = parseObject(queue.queues); const queueRows = Object.entries(queues).map(([name, q]: [string, any]) => ({ name, depth: n(q?.depth), ok: q?.ok }));
  const nav = [["overview", "Overview"], ["trends", "Trends"], ["traffic", "Traffic"], ["database", "Database"], ["queue", "Queue"], ["security", "Security"], ["ux", "UX"], ["business", "Business"], ["incidents", "Incidents"]];

  return <main>
    <header className="hero"><div><p className="eyebrow">SMW Mission Control</p><h1>Ops Engine</h1><p className="subtitle">Professional external monitoring console for SWE, SRE, and DevSecOps visibility across sunnysir.com. Data is pushed out from the droplet, so the dashboard remains useful even when SMW is degraded.</p></div><button className="refresh" onClick={() => void load()} disabled={loading}><RefreshCw className={loading ? "spin" : ""} size={18} /> Refresh</button></header>
    <nav className="navDock">{nav.map(([href, label]) => <a href={`#${href}`} key={href}>{label}</a>)}</nav>
    {error ? <section className="banner bad"><WifiOff size={18} /> Unable to load Ops Engine API: {error}</section> : null}

    <Section id="overview" eyebrow="Current State" title="Production overview" subtitle={`Last refresh ${lastRefresh ? formatAgo(lastRefresh) : "never"}`}>
      <div className="grid metrics"><MetricCard title="Overall status" value={status.toUpperCase()} detail={`Heartbeat ${formatAgo(heartbeat?.received_at)}`} icon={statusClass(status) === "good" ? <CheckCircle2 /> : <AlertTriangle />} tone={statusClass(status)} /><MetricCard title="Host" value={heartbeat?.hostname || "unknown"} detail={`${heartbeat?.source || "no source"} · uptime ${fmtUptime(server?.uptime_seconds)}`} icon={<Server />} /><MetricCard title="Disk used" value={`${summary?.disk_used_pct ?? server?.disk_used_pct ?? "—"}%`} detail={`load ${server?.load1 ?? "—"} / ${server?.load5 ?? "—"} / ${server?.load15 ?? "—"}`} icon={<HardDrive />} tone={n(summary?.disk_used_pct) >= 90 ? "bad" : n(summary?.disk_used_pct) >= 80 ? "warn" : "good"} /><MetricCard title="Memory used" value={`${summary?.memory_used_pct ?? server?.memory_used_pct ?? "—"}%`} detail={`${server?.cpu_count ?? "—"} CPU cores`} icon={<Activity />} tone={n(summary?.memory_used_pct) >= 95 ? "bad" : n(summary?.memory_used_pct) >= 85 ? "warn" : "good"} /><MetricCard title="Backup age" value={backup?.latest_backup_age_hours != null ? `${backup.latest_backup_age_hours}h` : "—"} detail={backup?.status || "latest detected backup"} icon={<Database />} tone={statusClass(backup?.status)} /><MetricCard title="Open incidents" value={incidents.length} detail={incidents.length ? "needs attention" : "clear"} icon={<ShieldAlert />} tone={incidents.length ? "bad" : "good"} /></div>
      <div className="grid four" style={{ marginTop: 16 }}><MetricCard title="Deploy" value={deployment?.short_sha || latest?.deploy?.short_sha || "—"} detail={`${deployment?.current_branch || latest?.deploy?.branch || "unknown"}${deployment?.is_dirty || latest?.deploy?.is_dirty ? " · dirty" : ""}`} icon={<GitBranch />} /><MetricCard title="API requests" value={apiTraffic?.total_requests ?? "—"} detail={`last ${apiTraffic?.window_seconds || 3600}s`} icon={<Code2 />} /><MetricCard title="API 5xx" value={apiTraffic?.total_5xx ?? "—"} detail={`4xx: ${apiTraffic?.total_4xx ?? "—"}`} icon={<AlertTriangle />} tone={n(apiTraffic?.total_5xx) > 0 ? "bad" : "good"} /><MetricCard title="Request events" value={requestSummary?.total_events ?? 0} detail={`${requestSummary?.unique_user_hashes ?? 0} users · ${requestSummary?.unique_ip_hashes ?? 0} IP hashes`} icon={<Users />} /></div>
    </Section>

    <Section id="trends" eyebrow="Historical Trends" title="Operational trends" subtitle="Compact charts use the history API, not only latest snapshots."><div className="grid two"><div className="panel"><div className="panelHeader"><div><p className="eyebrow">Server</p><h3>Resource trends</h3></div><span className="muted">{histServer.length} samples</span></div><div className="chartStack"><Sparkline label="Disk used" values={diskTrend} tone="good" suffix="%" /><Sparkline label="Memory used" values={memoryTrend} tone="warn" suffix="%" /><Sparkline label="Load 1m" values={loadTrend} tone="good" /></div></div><div className="panel"><div className="panelHeader"><div><p className="eyebrow">Traffic</p><h3>Requests and errors</h3></div><span className="muted">{histTraffic.length} samples</span></div><div className="chartStack"><Sparkline label="Requests/window" values={requestTrend} tone="good" /><Sparkline label="5xx/window" values={errorTrend} tone="bad" /><Sparkline label="Latency ms" values={latencyTrend} tone="good" /><HeatStrip items={histUptime.length ? histUptime : uptime} /></div></div></div></Section>

    <Section id="traffic" eyebrow="Traffic Intelligence" title="API traffic and request telemetry"><div className="grid two"><div className="panel"><div className="panelHeader"><div><p className="eyebrow">Distribution</p><h3>Status, roles, endpoints</h3></div></div><div className="chartStack"><BarChart data={statusChart.length ? statusChart : [{ label: "none", value: 0 }]} /><BarChart data={roleChart.length ? roleChart : [{ label: "none", value: 0 }]} /><BarChart data={endpointChart.length ? endpointChart : [{ label: "none", value: 0 }]} /></div></div><div className="panel"><div className="panelHeader"><div><p className="eyebrow">Recent</p><h3>Request duration</h3></div></div><Sparkline label="Request duration ms" values={durationTrend} tone="warn" /><div className="statusList" style={{ marginTop: 14 }}>{topPaths.slice(0, 8).map((p: any, i: number) => <StatusRow key={i} name={p.path || p.endpoint || "unknown"} status="live" detail={`${p.count || 0} requests`} />)}</div></div></div></Section>

    <Section id="database" eyebrow="SWE / Database" title="Database monitoring"><div className="grid three"><div className="panel"><div className="panelHeader"><div><p className="eyebrow">Postgres</p><h3>Connection health</h3></div><span className={`pill ${statusClass(database?.status)}`}>{database?.status || "unknown"}</span></div><div className="kvGrid"><KV label="Connections" value={database?.connections ?? "—"} /><KV label="Active" value={database?.active_connections ?? "—"} /><KV label="Idle" value={database?.idle_connections ?? "—"} /><KV label="Waiting" value={database?.waiting_queries ?? "—"} /></div></div><div className="panel"><div className="panelHeader"><div><p className="eyebrow">Storage</p><h3>DB size and reliability</h3></div></div><div className="kvGrid"><KV label="DB size" value={fmtBytes(database?.database_size_bytes)} /><KV label="Deadlocks" value={database?.deadlocks ?? "—"} /><KV label="Commits" value={database?.xact_commit ?? "—"} /><KV label="Rollbacks" value={database?.xact_rollback ?? "—"} /></div></div><div className="panel"><div className="panelHeader"><div><p className="eyebrow">Slow queries</p><h3>Active query risk</h3></div></div><KV label="Slow active queries" value={database?.slow_active_queries ?? "—"} /></div></div></Section>

    <Section id="queue" eyebrow="SRE / Workers" title="Queue and worker monitoring"><div className="grid three"><MetricCard title="Total queue depth" value={queue?.total_depth ?? 0} detail="Redis/Celery LLEN total" icon={<Activity />} tone={n(queue?.total_depth) > 100 ? "bad" : n(queue?.total_depth) > 20 ? "warn" : "good"} /><MetricCard title="Worker service" value={queue?.worker_service?.status || "unknown"} detail={queue?.worker_service?.enabled || "systemd"} icon={<Server />} tone={statusClass(queue?.worker_service?.status)} /><MetricCard title="Beat service" value={queue?.beat_service?.status || "unknown"} detail={queue?.beat_service?.enabled || "systemd"} icon={<Clock />} tone={statusClass(queue?.beat_service?.status)} /></div><div className="panel" style={{ marginTop: 16 }}><div className="panelHeader"><div><p className="eyebrow">Queues</p><h3>Depth by queue</h3></div></div><BarChart data={queueRows.length ? queueRows.map((q) => ({ label: q.name, value: q.depth, tone: q.depth > 100 ? "bad" : q.depth > 20 ? "warn" : "good" })) : [{ label: "celery", value: 0, tone: "good" }]} /></div></Section>

    <Section id="security" eyebrow="DevSecOps" title="Security and error intelligence"><div className="grid three"><MetricCard title="Fail2ban events" value={security?.fail2ban_events ?? 0} detail={`${security?.fail2ban_bans ?? 0} bans · ${security?.fail2ban_unbans ?? 0} unbans`} icon={<ShieldAlert />} tone={n(security?.fail2ban_bans) > 0 ? "warn" : "good"} /><MetricCard title="Nginx errors" value={security?.nginx_error_lines ?? 0} detail="last collection window" icon={<AlertTriangle />} tone={n(security?.nginx_error_lines) > 0 ? "warn" : "good"} /><MetricCard title="Error groups" value={errors.length} detail="Sentry-lite grouping" icon={<Code2 />} tone={errors.length ? "bad" : "good"} /></div><div className="grid two" style={{ marginTop: 16 }}><div className="panel"><div className="panelHeader"><div><p className="eyebrow">Error groups</p><h3>Latest groups</h3></div></div><div className="statusList">{errors.length ? errors.slice(0, 8).map((e) => <StatusRow key={e.id} name={e.fingerprint} status={e.latest_severity || "error"} detail={`${e.count} · ${e.latest_path || "no path"}`} />) : <StatusRow name="No error groups" status="live" detail="clear" />}</div></div><div className="panel"><div className="panelHeader"><div><p className="eyebrow">Coverage</p><h3>Implementation map</h3></div></div><div className="coverageGrid"><CoverageCard title="Production Health" detail="Status, uptime, services, disk, memory, request volume, errors." /><CoverageCard title="Live Traffic Monitoring" detail="Endpoint traffic, request IDs, roles, latency and status distribution." /><CoverageCard title="Incident Operations" detail="Open incidents, auto-resolve, Telegram alerts, uptime checks." /><CoverageCard title="Deployment Visibility" detail="Current branch/SHA, dirty state, commit metadata." /><CoverageCard title="Infrastructure Monitoring" detail="Droplet disk/memory/load/services live." /><CoverageCard title="Security / DevSecOps" detail="Fail2ban, nginx, Sentry-lite error grouping." /><CoverageCard title="Database Monitoring" detail="Postgres stats collector is live." /><CoverageCard title="Queue / Worker Monitoring" detail="Celery/Redis queue collector is live." /><CoverageCard title="User Experience" detail="RUM contract and JSONL collector are live." /><CoverageCard title="Business Impact" detail="SMW business counters are live." /></div></div></div></Section>

    <Section id="ux" eyebrow="Frontend Experience" title="User experience monitoring"><div className="grid four"><MetricCard title="RUM events" value={ux?.events ?? 0} detail={ux?.source || "rum-jsonl"} icon={<Activity />} tone="good" /><MetricCard title="Avg LCP" value={ux?.avg_lcp_ms != null ? `${ux.avg_lcp_ms}ms` : "—"} detail="largest contentful paint" icon={<Clock />} /><MetricCard title="Avg INP" value={ux?.avg_inp_ms != null ? `${ux.avg_inp_ms}ms` : "—"} detail="interaction latency" icon={<Activity />} /><MetricCard title="JS errors" value={ux?.js_errors ?? 0} detail={ux?.note || "browser errors"} icon={<AlertTriangle />} tone={n(ux?.js_errors) ? "bad" : "good"} /></div></Section>

    <Section id="business" eyebrow="Business Impact" title="SMW business counters"><div className="grid four"><MetricCard title="Pending admissions" value={business?.pending_admissions ?? "—"} detail="from SMW health summary" icon={<Users />} /><MetricCard title="Payments" value={business?.payments ?? "—"} detail="current counter" icon={<Database />} /><MetricCard title="Users" value={business?.users ?? "—"} detail="registered users" icon={<Users />} /><MetricCard title="Source" value={business?.source || "—"} detail={business?.status || "unknown"} icon={<Server />} tone={statusClass(business?.status)} /></div></Section>

    <Section id="incidents" eyebrow="Operations" title="Incidents, services, and request events"><div className="grid two"><div className="panel"><div className="panelHeader"><div><p className="eyebrow">Incidents</p><h3>Open incidents</h3></div></div><div className="statusList">{incidents.length ? incidents.map((i) => <StatusRow key={i.id} name={i.title} status={i.severity} detail={`${i.source} · ${formatAgo(i.started_at)}`} />) : <StatusRow name="No open incidents" status="live" detail="clear" />}</div></div><div className="panel"><div className="panelHeader"><div><p className="eyebrow">Services</p><h3>Latest service snapshots</h3></div></div><div className="statusList">{services.slice(0, 12).map((s, i) => <StatusRow key={`${s.service_name}-${i}`} name={s.service_name} status={s.status} detail={formatAgo(s.checked_at)} />)}</div></div></div><div className="panel" style={{ marginTop: 16 }}><div className="panelHeader"><div><p className="eyebrow">Sanitized Request Telemetry</p><h3>Recent API events</h3></div><span className="muted">hashed identifiers only</span></div><div className="tableWrap"><table><thead><tr><th>Time</th><th>Request ID</th><th>Method</th><th>Endpoint</th><th>Status</th><th>Duration</th><th>Role</th><th>User Hash</th><th>IP Hash</th></tr></thead><tbody>{requestEvents.length ? requestEvents.map((ev, idx) => <tr key={`${ev?.request_id || idx}-${idx}`}><td>{formatAgo(ev?.ts)}</td><td><code>{ev?.request_id || "—"}</code></td><td>{ev?.method}</td><td><code>{ev?.endpoint}</code></td><td><span className={`pill ${ev?.status >= 500 ? "bad" : ev?.status >= 400 ? "warn" : "good"}`}>{ev?.status}</span></td><td>{ev?.duration_ms}ms</td><td>{ev?.role}</td><td><code>{ev?.hashed_user_id || "—"}</code></td><td><code>{ev?.hashed_ip || "—"}</code></td></tr>) : <tr><td colSpan={9}>No request events yet.</td></tr>}</tbody></table></div></div></Section>
  </main>;
}
createRoot(document.getElementById("root")!).render(<App />);
